name: "Terraform workflow for Destroy"

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN : ${{ secrets.AWS_SESSION_TOKEN }}
  TF_WORKSPACE: project4

jobs:
  job1:
    name: "Terraform Init"
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform Format
      id: fmt
      run: terraform fmt 

    - name: Terraform Init
      id: init
      run: terraform init

  job2:
    name: "Terraform Plan and Destroy"
    runs-on: [self-hosted, windows, x64]
    needs: job1
    

    steps:
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: terraform plan 

    
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve  
